language: node_js
node_js:
  - "12.4.0"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

installs:

  - npm install

script:
  - npm run ci

test:
  adapter: mysql
  database: "career_lattice"
  username: "user"
  encoding: utf8