dist: trusty 
sudo: false 

language: node_js
node_js:
  - "12.4.0"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
    - ./node_modules


installs:
  - npm install
  - npm install ng-common
  - npm install angular
  - npm install express
  - npm install mysql

script:
  - ng test