dist: trusty
sudo: required
language: node_js
node_js:
- 12.5.0
addons:
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - openssl aes-256-cbc -K $encrypted_c9b12307f510_key -iv $encrypted_c9b12307f510_iv -in privateKey.js.enc -out privateKey.js -d
install:
- cd Angular/
- npm install
script:
- ng test --watch=false --browsers=ChromeHeadless